config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "recipes/index"
  get "recipes/show"
  get "pages/index"

  resources :users, only: [:show]
  resources :favourite_recipes, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favourite_recipe.rb
class FavouriteRecipe < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :recipe_id, uniqueness: :true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, :cook_time, :prep_time, :ingredients, presence: true
  validates :title, uniqueness: true

  has_many :favourite_recipes

  def self.filtered_and_sorted(params)
    ingredients = params[:ingredients]
    sort_by = params[:sort_by]

    recipes = search_by_ingredients(ingredients)
    recipes = recipes.sort_by_criteria(sort_by) if sort_by.present?
    recipes
  end

  def decoded_image_url
    return unless image.present? && image.include?('url=')

    CGI.unescape(image.split('url=').last)
  end

  private

  def self.search_by_ingredients(ingredients)
    return all if ingredients.blank?

    # Split the query into individual ingredients
    ingredients = ingredients.downcase.split

    # Match recipes containing any of the ingredients
    conditions = build_conditions(ingredients)
    values = build_values(ingredients)

    where(conditions, *values)
  end

  def self.sort_by_criteria(sort_by)
    case sort_by
    when 'time'
      order(Arel.sql('prep_time + cook_time ASC')) # Sort by combined prep + cook time
    when 'rating'
      order(ratings: :desc)
    else
      order(title: :asc) # Default sort, alphabetical I guess?
    end
  end

  def self.build_conditions(ingredients)
    # create a comparison condition and set up the query string to combine the ingredients
    ingredients.map { "LOWER(ingredients) LIKE ?" }.join(' AND ')
  end

  def self.build_values(ingredients)
    # produce the string of ingredients separated by spaces,
    # to be substituted into the ? part of the query string
    ingredients.map { |ingredient| "%#{ingredient}%" }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favourite_recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include Pagy::Backend
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/favourite_recipes_controller.rb
class FavouriteRecipesController < ApplicationController
  before_action :set_recipe, only: :create
  before_action :set_favourite_recipe, only: :destroy

  def create
    favourite_recipe = FavouriteRecipe.new(user: current_user, recipe: @recipe)

    if favourite_recipe.save
      redirect_to :pages_index, notice: 'Recipe was successfully added to favourites.'
    else
      redirect_to :pages_index, notice: 'You already have this recipe favourited'
    end
  end

  def destroy
    if @favourite_recipe.destroy
      redirect_to user_path(current_user), notice: 'Recipe was successfully deleted.'
    else
      redirect_to user_path(current_user), alert: 'Failed to delete the recipe.'
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def set_favourite_recipe
    @favourite_recipe = FavouriteRecipe.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include Pagy::Backend

  def index
    @user = current_user
    @pagy, @recipes = pagy(Recipe.filtered_and_sorted(params), items: 20)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @favourite_recipes = @user.favourite_recipes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/favourite_recipes_helper.rb
module FavouriteRecipesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Nice Recipes App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= stylesheet_link_tag "homepage", media: "all" %>

<div class="container">
  <header class="header">
    <% if user_signed_in? %>
      <h1>Welcome back to Nice Recipes, <%= current_user.email %></h1>
      <%= link_to 'My Profile and Favourite Recipes', user_path(current_user), class: "btn btn-info profile-button" %>
      <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-danger signout-button" %>
  <% else %>
      <h1>Nice Recipes</h1>
      <%= link_to 'Sign in', new_user_session_path, class: "btn btn-info profile-button" %>
    <% end %>
    <p class="subtitle">Find the perfect recipe by searching for ingredients you have!</p>
  </header>

  <div class="search-bar">
    <%= form_with url: pages_index_path, method: :get, local: true, class: "search-form" do %>
      <%= text_field_tag :ingredients, params[:ingredients], placeholder: "Search by ingredients (e.g., 'chicken rice')", class: "search-input" %>
      <%= select_tag :sort_by, options_for_select([['Prep + Cook Time', 'time'], ['Rating', 'rating']], params[:sort_by]), class: "form-select" %>
      <%= submit_tag "Search", class: "btn btn-primary search-button" %>
    <% end %>
  </div>

  <div class="pag-bar mt-5 pt-5">
    <%== pagy_nav(@pagy) %>
  </div>
  <table class="recipe-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Cook Time (min)</th>
        <th>Prep Time (min)</th>
        <th>Ingredients</th>
        <th>Ratings</th>
        <th>Cuisine</th>
        <th>Category</th>
        <th>Author</th>
        <th>Image</th>
        <% if @user.present? %>
          <th>Favourite</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
    <% if @recipes.any? %>
      <% @recipes.each do |recipe| %>
        <tr>
          <td><%= recipe.title %></td>
          <td><%= recipe.cook_time %></td>
          <td><%= recipe.prep_time %></td>
          <td class="ingredients">
            <% recipe.ingredients.split(',').each do |ingredient| %>
              <%= ingredient.strip %>
            <% end %>
          </td>
          <td><%= recipe.ratings %></td>
          <td><%= recipe.cuisine %></td>
          <td><%= recipe.category %></td>
          <td><%= recipe.author %></td>
          <td>
            <% if recipe.decoded_image_url %>
              <img src="<%= recipe.decoded_image_url %>" alt="Recipe Image" class="recipe-image">
            <% else %>
              No image available
            <% end %>
          </td>
          <% if @user.present? %>
            <td><%= link_to 'Add to Favourite Recipes', favourite_recipes_path(recipe_id: recipe.id), data: { turbo_method: "post" } %></td>
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="8" class="no-results">No recipes found.</td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <div class="pag-bar mt-5 pt-5">
    <%== pagy_nav(@pagy) %>
  </div>
</div>

app/views/recipes/index.html.erb
<h1>Recipes#index</h1>
<p>Find me in app/views/recipes/index.html.erb</p>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <%= @user.email %>
  <h1>Favourite Recipes</h1>
  <table class="recipe-table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Cook Time (min)</th>
      <th>Prep Time (min)</th>
      <th>Ingredients</th>
      <th>Ratings</th>
      <th>Cuisine</th>
      <th>Category</th>
      <th>Author</th>
      <th>Remove from favourites</th>
    </tr>
    </thead>
    <tbody>
  <% if @favourite_recipes.any? %>
    <% @favourite_recipes.each do |favourite_recipe| %>
    <% recipe = Recipe.find(favourite_recipe.recipe_id) %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.cook_time %></td>
        <td><%= recipe.prep_time %></td>
        <td class="ingredients">
          <% recipe.ingredients.split(',').each do |ingredient| %>
            <%= ingredient.strip %>
          <% end %>
        </td>
        <td><%= recipe.ratings %></td>
        <td><%= recipe.cuisine %></td>
        <td><%= recipe.category %></td>
        <td><%= recipe.author %></td>
        <td><%= link_to 'Remove from Favourite Recipes', favourite_recipe_path(id: favourite_recipe.id), data: { turbo_method: "delete" } %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="8" class="no-results">No recipes favourited yet. Try Clicking the favourite button on the home page!</td>
    </tr>
  <% end %>

  <%= link_to 'Back to home', pages_index_path %>
</div>